### PR TITLE
add config, install resources

### LINKED ISSUE #7: Configuration settings: bind to
Please make it easy to set some configuration knobs (without overwriting the entire netdata.conf file). Primarily setting `bind to` so it's not listening publicly.

### PR DESCRIPTION
**Pull request by nictrix**
fixes #7 

From our previous discussions; I've made quite a few updates to the cookbook. I saw duplication occurring with the other python plugin resources, so I've collapsed them into one and deprecated the others. I also tried to update the supporting files to more closely match other community cookbooks; though I did keep the Gemfile, Rakefile (we could mimic this style of cookbook testing: https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD) if you want.

- updated what operating systems the cookbook supported
- removed unique rubocop rules and moved to adhering to https://github.com/chef/cookstyle
- `netdata_bind_rndc_conf` & `netdata_nginx_conf` are deprecated in favor of the new `netdata_python_plugin` resource
- created `netdata_install` resource
- created `netdata_config` resource
- kept backwards compatibility, but provided deprecation notices for future releases that would remove the recipes, attributes
- converted from serverspec to inspec to more closely follow community cookbooks
- added more inspec tests because I couldn't run unit tests against the content made with `netdata_config` (using accumulator pattern)
- updated unit tests to match deprecations (also we might want to put these under spec/unit/recipes) folder structure to align with community cookbooks

I didn't create resources for stream, health, app_groups, node, statsd, etc.. as the current proposed changes are already large enough and I wanted to get acceptance of `netdata_python_plugin`. (future PRs can handle resources that manage those configs)

When you read through some of the deprecations, here are my thoughts around them in future updates:
- move /tmp/netdata git source directory to /opt/netdata.git to provide a more stable autoupdate feature
- use resources and remove all recipes, attributes; allowing this cookbook to become a library cookbook
- when moving to a breaking change cookbook; remove the deprecated resources, remove thoses tests, and update fixture cookbook, including inspec tests
- move logic to python_plugin to install the necessary system packages automatically instead of using `node['netdata']['plugins']['python']['mysql']['enabled']`

Thanks for considering my PR and I look forward to your feedback!

### CODE REVIEW

**Comment by nictrix** [comment]
Quick note, I just realized the `netdata_install` resource is not restarting the service, I'm looking for examples and a solution to this problem, will comment once I have that fixed in this PR.

**Comment by nictrix** [comment]
Alright, I've resolved the issue with the service not restarting after config changes for `netdata_config`. I also ran `bundle exec rake test:integration` which ran through all operating systems successfully.

**Comment by nictrix** [comment]
@sergiopena @jmadureira I know this is a huge PR - I didn't expect it to turn out this way, but one optimization lead to another and this is where it took me. I can break the changes up into multiple subsequent PRs if that helps decrease the number of things to look through.

Just let me know, looking for feedback and open to suggestions/changes as required.

**Comment by jmadureira** [comment]
Hello @nictrix 

Sorry for my absence as I didn't have enough time to give a proper review to your changes.
Nevertheless thank you for your work. I had already made some of these changes myself so you saved me some time :)

My only remark is with the deprecation of the default netdata recipe. I agree that the installation process can be provided via chef resource but having a recipe that is simply a wrapper for that resource gives users a cleaner mechanism of installing netdata. I have several cases myself where I simply include the recipe on my run list because the default installation is more than enough.

What do you think?

**Comment by nictrix** [comment]
@sergiopena thanks for the approval

@jmadureira I think that is more than reasonable and I can update the cookbook to keep that functionality.

**Comment by nictrix** [comment]
Updated with the changes @jmadureira wanted. Ran through style, unit and integration tests just to make sure everything is still looking good!

This PR is ready for approval/merge.

**Pull request merged**
